insert into enfermera(idenfermera,nombre,apellido,correo,contraseña) values (88874613,'Harper','Stewart','harper4349@gmail.com','qsLNqCSOLBx');
insert into enfermera(idenfermera,nombre,apellido,correo,contraseña) values (56626489,'Amelia','Gray','amelia9921@outlook.com','EcVCuwKvZA2ru4y0KP6');        
insert into enfermera(idenfermera,nombre,apellido,correo,contraseña) values (92031561,'Isabella','Johnson','isabella5045@outlook.com','V2IBJoM48Mh0G3N5YQx'); 
insert into enfermera(idenfermera,nombre,apellido,correo,contraseña) values (16433821,'Ahmed','Cooper','ahmed9727@outlook.com','akq5e5Y9iF4o0vF2WDW5p');      
insert into enfermera(idenfermera,nombre,apellido,correo,contraseña) values (33527291,'Emily','Flores','emily9890@outlook.com','rvTzoQfISNMklJFaxnW7ppp');    
insert into enfermera(idenfermera,nombre,apellido,correo,contraseña) values (38000952,'Evelyn','Torres','evelyn6744@gmail.com','MKFfLswVPu');
insert into enfermera(idenfermera,nombre,apellido,correo,contraseña) values (93591596,'Victoria','Baker','victoria6869@outlook.com','R9ECl4Gm');
insert into enfermera(idenfermera,nombre,apellido,correo,contraseña) values (61149305,'Madison','Mitchell','madison2854@gmail.com','dgfAlXswhyuLyWADlo5pFqi');
insert into enfermera(idenfermera,nombre,apellido,correo,contraseña) values (26498232,'Stella','Torres','stella5282@outlook.com','m3BvLoLRLd0Q');
insert into enfermera(idenfermera,nombre,apellido,correo,contraseña) values (23338275,'Madison','Griffin','madison9781@gmail.com','4DAr00MviS28C0rJV');       
insert into enfermera(idenfermera,nombre,apellido,correo,contraseña) values (89855781,'Aurora','Torres','aurora5311@outlook.com','JVUY2rKwetYxneBI');
insert into enfermera(idenfermera,nombre,apellido,correo,contraseña) values (14215031,'Sergio','Hayes','sergio5283@gmail.com','1xTHqM6Pa');
insert into enfermera(idenfermera,nombre,apellido,correo,contraseña) values (21141735,'Sofia','Stewart','sofia4056@hotmail.com','PoznMwV5xvAV4Rd');
insert into enfermera(idenfermera,nombre,apellido,correo,contraseña) values (86775681,'Charlotte','Ramirez','charlotte7836@outlook.com','oC6bAIlERKRYp11K');
insert into enfermera(idenfermera,nombre,apellido,correo,contraseña) values (85582403,'Sergio','Rodriguez','sergio2677@outlook.com','b5F4e8okmK8yflJ');

insert into tiposangre(idtiposangre) values('A+');
insert into tiposangre(idtiposangre) values('A-');
insert into tiposangre(idtiposangre) values('B+');
insert into tiposangre(idtiposangre) values('B-');
insert into tiposangre(idtiposangre) values('AB+');
insert into tiposangre(idtiposangre) values('AB-');
insert into tiposangre(idtiposangre) values('O+');
insert into tiposangre(idtiposangre) values('O-');
insert into tiposangre(idtiposangre) values('N.A');


insert into laboratorio(nroLaboratorio,Especialidad) values (385,'Bioquímica');
insert into laboratorio(nroLaboratorio,Especialidad) values (182,'Microbiología');     
insert into laboratorio(nroLaboratorio,Especialidad) values (753,'Inmunología');       
insert into laboratorio(nroLaboratorio,Especialidad) values (231,'Genética');
insert into laboratorio(nroLaboratorio,Especialidad) values (892,'Farmacología');      
insert into laboratorio(nroLaboratorio,Especialidad) values (844,'Hematología');       
insert into laboratorio(nroLaboratorio,Especialidad) values (682,'Virología');
insert into laboratorio(nroLaboratorio,Especialidad) values (279,'Patología');
insert into laboratorio(nroLaboratorio,Especialidad) values (235,'Toxicología');       
insert into laboratorio(nroLaboratorio,Especialidad) values (855,'Epidemiología');     
insert into laboratorio(nroLaboratorio,Especialidad) values (324,'Biología-Molecular');
insert into laboratorio(nroLaboratorio,Especialidad) values (868,'Química');
insert into laboratorio(nroLaboratorio,Especialidad) values (653,'Analítica');
insert into laboratorio(nroLaboratorio,Especialidad) values (497,'Anatomía');
insert into laboratorio(nroLaboratorio,Especialidad) values (209,'Patológica');        
insert into laboratorio(nroLaboratorio,Especialidad) values (313,'Citología');
insert into laboratorio(nroLaboratorio,Especialidad) values (561,'Biomedicina');       
insert into laboratorio(nroLaboratorio,Especialidad) values (274,'Bioinformática');    
insert into laboratorio(nroLaboratorio,Especialidad) values (275,'Neurociencia');      
insert into laboratorio(nroLaboratorio,Especialidad) values (978,'Biotecnología');     
insert into laboratorio(nroLaboratorio,Especialidad) values (783,'Fisiología');        
insert into laboratorio(nroLaboratorio,Especialidad) values (494,'Investigación');   


insert into paciente(dni,nombre,apellido) values ('35833304','Muhammad','Edwards');  
insert into paciente(dni,nombre,apellido) values ('40877174','Sofia','Hayes');       
insert into paciente(dni,nombre,apellido) values ('15999601','Victoria','James');    
insert into paciente(dni,nombre,apellido) values ('56863052','Carlos','Ramirez');    
insert into paciente(dni,nombre,apellido) values ('50425548','Rafael','Hayes');      
insert into paciente(dni,nombre,apellido) values ('57948826','Stella','King');       
insert into paciente(dni,nombre,apellido) values ('75643450','Lucas','Lee');
insert into paciente(dni,nombre,apellido) values ('41430656','Zoe','Morris');        
insert into paciente(dni,nombre,apellido) values ('92300489','Amelia','Taylor');     
insert into paciente(dni,nombre,apellido) values ('61971001','Lily','Miller');       
insert into paciente(dni,nombre,apellido) values ('75906079','David','Flores');      
insert into paciente(dni,nombre,apellido) values ('34028395','Julian','Ramirez');    
insert into paciente(dni,nombre,apellido) values ('24604018','Sergio','Watson');     
insert into paciente(dni,nombre,apellido) values ('59672315','Victoria','Lopez');    
insert into paciente(dni,nombre,apellido) values ('86694526','Lucas','Martinez');    
insert into paciente(dni,nombre,apellido) values ('20273577','Grace','Taylor');      
insert into paciente(dni,nombre,apellido) values ('84368700','Madison','Murphy');
insert into paciente(dni,nombre,apellido) values ('85160243','Grace','Watson');
insert into paciente(dni,nombre,apellido) values ('29747858','Isabella','Moore');
insert into paciente(dni,nombre,apellido) values ('10744351','Daniel','Evans');
insert into paciente(dni,nombre,apellido) values ('90644351','Daniel','Gear');